export const GET_ALL_PERSONS_REQUESTED = 'GET_ALL_PERSONS_REQUESTED';
export const GET_ALL_PERSONS_SUCCESS = 'GET_ALL_PERSONS_SUCCESS';
export const GET_ALL_PERSONS_FAILED = 'GET_ALL_PERSONS_FAILED';

export const GET_BY_ID_PERSON_REQUESTED = 'GET_BY_ID_PERSON_REQUESTED';
export const GET_BY_ID_PERSON_SUCCESS = 'GET_BY_ID_PERSON_SUCCESS';
export const GET_BY_ID_PERSON_FAILED = 'GET_BY_ID_PERSON_FAILED';

export const POST_PERSON_REQUESTED = 'POST_PERSON_REQUESTED';
export const POST_PERSON_SUCCESS = 'POST_PERSON_SUCCESS';
export const POST_PERSON_FAILED = 'POST_PERSON_FAILED';

export const PUT_PERSON_REQUESTED = 'PUT_PERSON_REQUESTED';
export const PUT_PERSON_SUCCESS = 'PUT_PERSON_SUCCESS';
export const PUT_PERSON_FAILED = 'PUT_PERSON_FAILED';

export const DELETE_PERSON_REQUESTED = 'DELETE_PERSON_REQUESTED';
export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS';
export const DELETE_PERSON_FAILED = 'DELETE_PERSON_FAILED';

//////////////////////////////////////////////////

export const GET_ALL_RESTAURANTS_REQUESTED = 'GET_ALL_RESTAURANTS_REQUESTED';
export const GET_ALL_RESTAURANTS_SUCCESS = 'GET_ALL_RESTAURANTS_SUCCESS';
export const GET_ALL_RESTAURANTS_FAILED = 'GET_ALL_RESTAURANTS_FAILED';

export const GET_BY_NAME_RESTAURANTS_REQUESTED = 'GET_BY_NAME_RESTAURANTS_REQUESTED';
export const GET_BY_NAME_RESTAURANTS_SUCCESS = 'GET_BY_NAME_RESTAURANTS_SUCCESS';
export const GET_BY_NAME_RESTAURANTS_FAILED = 'GET_BY_NAME_RESTAURANTS_FAILED';

export const GET_BY_CATEGORY_RESTAURANTS_REQUESTED = 'GET_BY_CATEGORY_RESTAURANTS_REQUESTED';
export const GET_BY_CATEGORY_RESTAURANTS_SUCCESS = 'GET_BY_CATEGORY_RESTAURANTS_SUCCESS';
export const GET_BY_CATEGORY_RESTAURANTS_FAILED = 'GET_BY_CATEGORY_RESTAURANTS_FAILED';

export const GET_BY_ID_RESTAURANT_REQUESTED = 'GET_BY_ID_RESTAURANT_REQUESTED';
export const GET_BY_ID_RESTAURANT_SUCCESS = 'GET_BY_ID_RESTAURANT_SUCCESS';
export const GET_BY_ID_RESTAURANT_FAILED = 'GET_BY_ID_RESTAURANT_FAILED';

export const POST_RESTAURANT_REQUESTED = 'POST_RESTAURANT_REQUESTED';
export const POST_RESTAURANT_SUCCESS = 'POST_RESTAURANT_SUCCESS';
export const POST_RESTAURANT_FAILED = 'POST_RESTAURANT_FAILED';

export const PUT_RESTAURANT_REQUESTED = 'PUT_RESTAURANT_REQUESTED';
export const PUT_RESTAURANT_SUCCESS = 'PUT_RESTAURANT_SUCCESS';
export const PUT_RESTAURANT_FAILED = 'PUT_RESTAURANT_FAILED';

export const DELETE_RESTAURANT_REQUESTED = 'DELETE_RESTAURANT_REQUESTED';
export const DELETE_RESTAURANT_SUCCESS = 'DELETE_RESTAURANT_SUCCESS';
export const DELETE_RESTAURANT_FAILED = 'DELETE_RESTAURANT_FAILED';

//////////////////////////////////////////////////

export const GET_ALL_VISITS_REQUESTED = 'GET_ALL_VISITS_REQUESTED';
export const GET_ALL_VISITS_SUCCESS = 'GET_ALL_VISITS_SUCCESS';
export const GET_ALL_VISITS_FAILED = 'GET_ALL_VISITS_FAILED';

export const GET_BY_PERSON_ID_VISITS_REQUESTED = 'GET_BY_PERSON_ID_VISITS_REQUESTED';
export const GET_BY_PERSON_ID_VISITS_SUCCESS = 'GET_BY_PERSON_ID_VISITS_SUCCESS';
export const GET_BY_PERSON_ID_VISITS_FAILED = 'GET_BY_PERSON_ID_VISITS_FAILED';

export const GET_BY_ID_VISIT_REQUESTED = 'GET_BY_ID_VISIT_REQUESTED';
export const GET_BY_ID_VISIT_SUCCESS = 'GET_BY_ID_VISIT_SUCCESS';
export const GET_BY_ID_VISIT_FAILED = 'GET_BY_ID_VISIT_FAILED';

export const POST_VISIT_REQUESTED = 'POST_VISIT_REQUESTED';
export const POST_VISIT_SUCCESS = 'POST_VISIT_SUCCESS';
export const POST_VISIT_FAILED = 'POST_VISIT_FAILED';
export const POST_VISIT_CLEAR = 'POST_VISIT_CLEAR';

export const PUT_VISIT_REQUESTED = 'PUT_VISIT_REQUESTED';
export const PUT_VISIT_SUCCESS = 'PUT_VISIT_SUCCESS';
export const PUT_VISIT_FAILED = 'PUT_VISIT_FAILED';

export const DELETE_VISIT_REQUESTED = 'DELETE_VISIT_REQUESTED';
export const DELETE_VISIT_SUCCESS = 'DELETE_VISIT_SUCCESS';
export const DELETE_VISIT_FAILED = 'DELETE_VISIT_FAILED';